version: "3.8"
services:
  redis:
    image: "redis:7.2.1"
    container_name: "skillarc_redis"
    ports:
      - "127.0.0.1:6379:6379"
  postgres:
    image: "postgres:15.3"
    container_name: "skillarc_postgres"
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
  rails:
    tty: true
    stdin_open: true
    build:
      dockerfile: server.Dockerfile
    container_name: "skillarc_server"
    volumes:
      - .:/app
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
  resque:
    build:
      dockerfile: resque.Dockerfile
    container_name: "skillarc_resque"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
