---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/coaches/seekers":
    get:
      summary: Retrieve all seekers
      tags:
      - Coaches
      security:
      - bearer_auth: []
      parameters:
      - name: Key-Inflection
        in: header
        schema:
          type: string
          enum:
          - camel
          - dash
          - snake
          - pascale
      responses:
        '401':
          description: unauthenticated
        '200':
          description: retrieve all seekers
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/coach_seeker"
  "/coaches/seekers/{id}":
    get:
      summary: Retrieve a seekers
      tags:
      - Coaches
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: Key-Inflection
        in: header
        schema:
          type: string
          enum:
          - camel
          - dash
          - snake
          - pascale
      security:
      - bearer_auth: []
      responses:
        '401':
          description: unauthenticated
        '404':
          description: seeker not found
        '200':
          description: retrieve all seekers
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/coach_seeker"
  "/coaches/seekers/{id}/skill-levels":
    post:
      summary: Update a skill level
      tags:
      - Seekers
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: Key-Inflection
        in: header
        schema:
          type: string
          enum:
          - camel
          - dash
          - snake
          - pascale
      security:
      - bearer_auth: []
      responses:
        '401':
          description: unauthenticated
        '202':
          description: retrieve all seekers
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                level:
                  type: string
              required:
              - level
  "/coaches/seekers/{id}/assign_coach":
    post:
      summary: Update a skill level
      tags:
      - Seekers
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: Key-Inflection
        in: header
        schema:
          type: string
          enum:
          - camel
          - dash
          - snake
          - pascale
      security:
      - bearer_auth: []
      responses:
        '401':
          description: unauthenticated
        '404':
          description: Coach not found
        '202':
          description: retrieve all seekers
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                coachId:
                  type: string
                  format: uuid
              required:
              - coachId
  "/coaches/seekers/{id}/recommend_job":
    post:
      summary: Update a skill level
      tags:
      - Seekers
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: Key-Inflection
        in: header
        schema:
          type: string
          enum:
          - camel
          - dash
          - snake
          - pascale
      security:
      - bearer_auth: []
      responses:
        '401':
          description: unauthenticated
        '202':
          description: retrieve all seekers
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                jobId:
                  type: string
                  format: uuid
              required:
              - jobId
  "/coaches/seekers/{id}/certify":
    post:
      summary: Update a skill level
      tags:
      - Seekers
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: Key-Inflection
        in: header
        schema:
          type: string
          enum:
          - camel
          - dash
          - snake
          - pascale
      security:
      - bearer_auth: []
      responses:
        '401':
          description: unauthenticated
        '202':
          description: retrieve all seekers
  "/employers/applicants/{id}":
    put:
      summary: Update an applicants status
      tags:
      - Employers
      security:
      - bearer_auth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: Key-Inflection
        in: header
        schema:
          type: string
          enum:
          - camel
          - dash
          - snake
          - pascale
      responses:
        '401':
          description: unauthenticated
        '200':
          description: Applicant updated
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/applicant"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum:
                  - new
                  - pending intro
                  - intro made
                  - interviewing
                  - hire
                  - pass
                reasons:
                  nullable: true
                  type: array
                  items:
                    oneOf:
                    - type: string
                    - type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                        response:
                          type: string
                          format: uuid
              required:
              - status
  "/employers/jobs":
    get:
      summary: Retrieve employer jobs
      tags:
      - Employers
      security:
      - bearer_auth: []
      parameters:
      - name: Key-Inflection
        in: header
        schema:
          type: string
          enum:
          - camel
          - dash
          - snake
          - pascale
      responses:
        '401':
          description: unauthenticated
        '200':
          description: jobs retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  jobs:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                        employerId:
                          type: string
                          format: uuid
                        employerName:
                          type: string
                        name:
                          type: string
                        description:
                          type: string
                  applicants:
                    type: array
                    items:
                      "$ref": "#/components/schemas/employer_applicants"
                required:
                - jobs
                - applicants
  "/profiles":
    get:
      summary: Retrieve all seekers
      tags:
      - Seekers
      security:
      - bearer_auth: []
      parameters:
      - name: Key-Inflection
        in: header
        schema:
          type: string
          enum:
          - camel
          - dash
          - snake
          - pascale
      responses:
        '401':
          description: unauthenticated
        '200':
          description: profiles retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uuid
                    firstName:
                      type: string
                    lastName:
                      type: string
                    email:
                      type: string
                      format: email
                    trainingProvider:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: string
                            format: uuid
                          name:
                            type: string
  "/profiles/{id}":
    get:
      summary: Retrieve a seeker
      tags:
      - Seekers
      security:
      - bearer_auth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: Key-Inflection
        in: header
        schema:
          type: string
          enum:
          - camel
          - dash
          - snake
          - pascale
      responses:
        '404':
          description: Seeker not found
        '200':
          description: profiles retrieved
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/seeker"
  "/session":
    post:
      summary: Indicate a new session started
      tags:
      - Users
      security:
      - bearer_auth: []
      parameters:
      - name: Key-Inflection
        in: header
        schema:
          type: string
          enum:
          - camel
          - dash
          - snake
          - pascale
      responses:
        '401':
          description: unauthenticated
        '202':
          description: Session Started
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
  schemas:
    applicant:
      type: object
      properties:
        id:
          type: string
          format: uuid
        jobId:
          type: string
          format: uuid
        seekerId:
          type: string
          format: uuid
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    employer_applicants:
      type: object
      properties:
        id:
          type: string
          format: uuid
        jobId:
          type: string
          format: uuid
        chatEnabled:
          type: boolean
        createdAt:
          type: string
          format: date-time
        jobName:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        phoneNumber:
          type: string
          nullable: true
        profileLink:
          type: string
        programs:
          type: array
        statusReasons:
          type: array
          items:
            type: string
        status:
          type: string
    seeker:
      type: object
      properties:
        id:
          type: string
          format: uuid
        about:
          type: string
        userId:
          type: string
          format: uuid
        educationExperiences:
          type: array
          items:
            "$ref": "#/components/schemas/education_experience"
        hiringStatus:
          type: string
        industryInterests:
          type: array
          items:
            type: string
        isProfileEditor:
          type: boolean
        otherExperiences:
          type: array
          items:
            "$ref": "#/components/schemas/other_experience"
        personalExperience:
          type: array
          items:
            "$ref": "#/components/schemas/personal_experience"
        profileSkills:
          type: array
          items:
            "$ref": "#/components/schemas/profile_skill"
        reference:
          type: array
          items:
            "$ref": "#/components/schemas/reference_with_training_provider"
        stories:
          type: array
          items:
            "$ref": "#/components/schemas/stories"
        missingProfileItems:
          type: array
          items:
            type: string
            enum:
            - education
            - work
        user:
          "$ref": "#/components/schemas/user_with_training_provider"
    coach_seeker:
      type: object
      properties:
        seekerId:
          type: string
          format: uuid
        firstName:
          type: string
          nullable: true
        lastName:
          type: string
          nullable: true
        email:
          type: string
          format: email
          nullable: true
        phoneNumber:
          type: string
          nullable: true
        certifiedBy:
          type: string
          nullable: true
        skillLevel:
          type: string
          nullable: true
        lastActiveOn:
          type: string
          format: date-time
          nullable: true
        lastContacted:
          oneOf:
          - type: string
            format: date-time
          - type: string
            enum:
            - Never
          nullable: true
        assignedCoach:
          type: string
          nullable: true
        barriers:
          type: array
          items:
            "$ref": "#/components/schemas/seeker_barrier"
        stage:
          type: string
          enum:
          - seeker_created
        notes:
          type: array
          items:
            "$ref": "#/components/schemas/seeker_note"
        applications:
          type: array
          items:
            "$ref": "#/components/schemas/seeker_application"
        jobRecommendations:
          type: array
          items:
            type: string
            format: uuid
    seeker_barrier:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          format: uuid
    seeker_note:
      type: object
      properties:
        note:
          type: string
        noteId:
          type: string
          format: uuid
        noteTakenBy:
          type: string
          nullable: true
        date:
          type: string
          format: date-time
    seeker_application:
      type: object
      properties:
        status:
          type: string
        employerName:
          type: string
        jobId:
          type: string
          format: uuid
          nullable: true
        employmentTitle:
          type: string
          nullable: true
    other_experience:
      type: object
      properties:
        id:
          type: string
          format: uuid
        organizationName:
          type: string
        position:
          type: string
        startDate:
          type: string
        endDate:
          type: string
        isCurrent:
          type: boolean
        description:
          type: string
    education_experience:
      type: object
      properties:
        id:
          type: string
          format: uuid
        organizationName:
          type: string
          nullable: true
        title:
          type: string
          nullable: true
        graduationDate:
          type: string
          nullable: true
        gpa:
          type: string
          nullable: true
        activities:
          type: string
          nullable: true
    personal_experience:
      type: object
      properties:
        id:
          type: string
          format: uuid
        activity:
          type: string
        startDate:
          type: string
        endDate:
          type: string
        description:
          type: string
    profile_skill:
      type: object
      properties:
        id:
          type: string
          format: uuid
        description:
          type: string
          nullable: true
        masterSkill:
          "$ref": "#/components/schemas/master_skill"
    master_skill:
      type: object
      properties:
        id:
          type: string
          format: uuid
        skill:
          type: string
        type:
          type: string
          enum:
          - TECHNICAL
          - PERSONAL
    user:
      type: object
      additionalProperties: true
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        firstName:
          type: string
        lastName:
          type: string
        zipCode:
          type: string
          nullable: true
        phoneNumber:
          type: string
          nullable: true
    user_with_training_provider:
      allOf:
      - "$ref": "#/components/schemas/user"
      - type: object
        additionalProperties: true
        properties:
          seekerTrainingProviders:
            type: array
            items:
              "$ref": "#/components/schemas/seeker_training_provider"
    seeker_training_provider:
      type: object
      properties:
        programId:
          type: string
          format: uuid
        trainingProviderId:
          type: string
          format: uuid
    reference:
      type: object
      additionalProperties: true
      properties:
        referenceText:
          type: string
    training_provider:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          format: uuid
    reference_with_training_provider:
      allOf:
      - "$ref": "#/components/schemas/reference"
      - type: object
        additionalProperties: true
        properties:
          trainingProvider:
            "$ref": "#/components/schemas/training_provider"
          authorUser:
            "$ref": "#/components/schemas/user"
