---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/employers/jobs":
    get:
      summary: Retrieve employer jobs
      tags:
      - Employers
      security:
      - bearer_auth: []
      parameters:
      - name: Key-Inflection
        in: header
        schema:
          type: string
          enum:
          - camel
          - dash
          - snake
          - pascale
      responses:
        '401':
          description: unauthenticated
        '200':
          description: jobs retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  jobs:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                        employerId:
                          type: string
                          format: uuid
                        employerName:
                          type: string
                        name:
                          type: string
                        description:
                          type: string
                  applicants:
                    type: array
                    items:
                      "$ref": "#/components/schemas/employer_applicants"
                required:
                - jobs
                - applicants
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
  schemas:
    employer_applicants:
      type: object
      properties:
        id:
          type: id
          format: uuid
        jobId:
          type: id
          format: uuid
        chatEnabled:
          type: boolean
        createdAt:
          type: string
          format: date-time
        jobName:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        phoneNumber:
          type: string
          nullable: true
        profileLink:
          type: string
        programs:
          type: array
        statusReasons:
          type: array
          items:
            type: string
        status:
          type: string
