name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_ACTION_PAT_TOKEN }}

      - name: Build and Push Server Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./server.Dockerfile
          push: true
          tags: ghcr.io/skillarc-app/server:latest
  build-and-push-sidekiq:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_ACTION_PAT_TOKEN }}

      - name: Build and Push Sidekiq Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./sidekiq.Dockerfile
          push: true
          tags: ghcr.io/skillarc-app/sidekiq:latest
